name: Greetings

on: pull_request_target

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
     - uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
       with: 
        reviewers: "hi5a"
        token: ${{ secrets.BOT_TOKEN }}
